// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBL2YqvStcOOk06mTG3Fai8s24Ee7G-fjY',
    appId: '1:308409644241:web:36f4492888e2fcf8adc1f0',
    messagingSenderId: '308409644241',
    projectId: 'com-cipherschools-assign-3eeb1',
    authDomain: 'com-cipherschools-assign-3eeb1.firebaseapp.com',
    storageBucket: 'com-cipherschools-assign-3eeb1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHkiK24kyKQE0pu-3V08X9OQLHEz5nseo',
    appId: '1:308409644241:android:880dc6cb0d46b2a9adc1f0',
    messagingSenderId: '308409644241',
    projectId: 'com-cipherschools-assign-3eeb1',
    storageBucket: 'com-cipherschools-assign-3eeb1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4UYyzeQ7xOrw3zSXsoawps33RdeEJhC0',
    appId: '1:308409644241:ios:8b2bf6713f72c815adc1f0',
    messagingSenderId: '308409644241',
    projectId: 'com-cipherschools-assign-3eeb1',
    storageBucket: 'com-cipherschools-assign-3eeb1.appspot.com',
    androidClientId: '308409644241-mva9qadrog333v0ist3s44aqe4nu0sge.apps.googleusercontent.com',
    iosClientId: '308409644241-tfg15a6q4an6g8bg98k7i2jeov8br1do.apps.googleusercontent.com',
    iosBundleId: 'com.example.cipherxExpenseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4UYyzeQ7xOrw3zSXsoawps33RdeEJhC0',
    appId: '1:308409644241:ios:f0e10143c4fbae36adc1f0',
    messagingSenderId: '308409644241',
    projectId: 'com-cipherschools-assign-3eeb1',
    storageBucket: 'com-cipherschools-assign-3eeb1.appspot.com',
    androidClientId: '308409644241-mva9qadrog333v0ist3s44aqe4nu0sge.apps.googleusercontent.com',
    iosClientId: '308409644241-njjtm63ir2l08508qkdhgjqvlvqao2nu.apps.googleusercontent.com',
    iosBundleId: 'com.example.cipherxExpenseTracker.RunnerTests',
  );
}
